[module]
name = "TestMod"
title-id = 0x01007ef00011e000

[megaton]
version = "0.1.0"

[cargo]
enabled = true

[build] # *profile enabled*
sources = [
    "src",
    # "../botw-symbols/src",
]

includes = [
    "src", 
    "include",

    # "../botw/src",
    # "../botw/lib/agl/include",
    # "../botw/lib/gsys/include",
    # "../botw/lib/sead/include",
    # "../botw/lib/NintendoSDK/include",
    # "../botw-symbols/include",
    # "/opt/devkitpro/libnx/include/",
]

libpaths = [] # -L
libraries = [] # -l
ldscripts = [
    # "../botw-symbols/ld/ld150.ld",
    # "../botw-symbols/ld/toolkit150.ld",
]
objects = []

[build.flags] # https://megaton.pistonite.dev/config/build_flags.html
c = [
    "<default>",
    "-DNNSDK",
    "-DSWITCH",
    "-D__SWITCH__",
    "-DNN_SDK_MAJOR=4",
    "-DNN_SDK_MINOR=4",
    "-DNN_SDK_PATCH=0",
    "-DNN_WARE_MAJOR=4",
    "-DNN_WARE_MINOR=4",
    "-DNN_WARE_PATCH=0",
    # "-DBOTW_VERSION=150",
    # "-DBOTWTOOLKIT_TCP_SEND",
]
cxx = [
    "<default>",
    "-Wno-invalid-offsetof",
]

ld = [
    "<default>",
]

rust = [
]

cargo = [
    "<default>",
]

[check] # *profile enabled*
ignore = []
symbols = [
    "tm.sym"
    # "../botw-symbols/symbols/150/main.syms",
    # "../botw-symbols/symbols/150/rtld.syms",
    # "../botw-symbols/symbols/150/sdk.syms",
    # "../botw-symbols/symbols/150/subsdk0.syms",
]
disallowed-instructions = []
