# This is the single configuration for a megaton project,
# just like Cargo.toml for a rust project ... well,
# a Cargo.toml would also exists for a megaton project that has Rust.
[module]
name = "example"
title-id = 0x01007ef00011e000

[build]
sources = [
    "src",
    "../botw-symbols/src",

    # also include our generated sources
    # the new build tool should automatically include these
    "target/megaton-new/none/cxxsrc",
]

includes = [

    "src",
    "include",

    "../botw/src",
    "../botw/lib/agl/include",
    "../botw/lib/gsys/include",
    "../botw/lib/sead/include",
    "../botw/lib/NintendoSDK/include",
    "../botw-symbols/include",

    # also include our generated headers
    # the new build tool should automatically include these
    "target/megaton-new/none/include",
]
ldscripts = [
    "../botw-symbols/ld/ld150.ld",
    "../botw-symbols/ld/toolkit150.ld",
]

# also statically link our rust crate
# the new build tool should automatically include this
objects = ["target/aarch64-unknown-hermit/release/libexample_rs.a"]

[build.flags]
c = [
    "<default>",
    "-DNNSDK",
    "-DSWITCH",
    "-D__SWITCH__",
    "-DNN_SDK_MAJOR=4",
    "-DNN_SDK_MINOR=4",
    "-DNN_SDK_PATCH=0",
    "-DNN_WARE_MAJOR=4",
    "-DNN_WARE_MINOR=4",
    "-DNN_WARE_PATCH=0",
    "-DBOTW_VERSION=150",
    "-DBOTWTOOLKIT_TCP_SEND",
]
cxx = [
    "<default>",
    "-Wno-invalid-offsetof",
]


[check]
symbols = [
    "../botw-symbols/symbols/150/main.syms",
    "../botw-symbols/symbols/150/rtld.syms",
    "../botw-symbols/symbols/150/sdk.syms",
    "../botw-symbols/symbols/150/subsdk0.syms",
]
