version: '3'

tasks:
  build:
    cmds:
     - cargo run -p megaton-cmd --bin megaton -- build

  # this is to upload the mod to console via ftp
  upload:
    cmds:
      - lftp 192.168.0.170:5000 < scripts/lftp-upload.sh
