version: '3'

tasks:
  build:
    cmds:
     - cargo run -p megaton-cmd --bin megaton -- build -vv

  # this is to upload the mod to console via ftp
  upload:
    cmds:
      - lftp 192.168.0.170:5000 < scripts/lftp-upload.sh

  download:
    desc: Download logs and crash reports from console
    cmds:
    - mkdir -p target/crash_reports/dumps
    - mkdir -p target/logs
    - lftp 192.168.0.170:5000 < scripts/lftp-download.sh
