["Megaton contributors"]

"packages/cli/**/*.rs" = "MIT"
"packages/cli-build/**/*.rs" = "MIT"

# C files
"packages/lib/src/megaton/*.s" = "GPL-3.0-or-later"
"packages/lib/src/megaton/*.c" = "GPL-3.0-or-later"
"packages/lib/src/megaton/*.cpp" = "GPL-3.0-or-later"
"packages/lib/src/nximpl/*.s" = "GPL-3.0-or-later"
"packages/lib/include/exl/**/*.h" = "GPL-3.0-or-later"
"packages/lib/include/exl/**/*.hpp" = "GPL-3.0-or-later"
"packages/lib/include/exl_armv8/**/*.h" = "GPL-3.0-or-later"
"packages/lib/include/exl_armv8/**/*.hpp" = "GPL-3.0-or-later"
"packages/lib/include/megaton/*.h" = "GPL-3.0-or-later"
"packages/lib/include/megaton/*.hpp" = "GPL-3.0-or-later"
"packages/lib/include/megaton/__internal/*.h" = "GPL-3.0-or-later"
"packages/lib/include/megaton/__internal/*.hpp" = "GPL-3.0-or-later"
"packages/lib/include/megaton/__priv/*.h" = "GPL-3.0-or-later"
"packages/lib/include/megaton/__priv/*.hpp" = "GPL-3.0-or-later"
"packages/test-mod/src/*.cpp" = "GPL-3.0-or-later"
"packages/test-mod/src/*.c" = "GPL-3.0-or-later"
"packages/test-mod/include/*.h" = "GPL-3.0-or-later"
"packages/test-mod/include/*.hpp" = "GPL-3.0-or-later"

# Rust files
"packages/lib/**/*.rs" = "GPL-3.0-or-later"
"packages/test-mod/**/*.rs" = "GPL-3.0-or-later"
"packages/toolchain-build/*.rs" = "MIT"

# Unmodified files
# ["libnx Authors"]
# "packages/lib/src/external/libnx/*.s" = "ISC"
# ["Matthew Conte"]
# "packages/lib/include/megaton/__external/tlsf.h" = "BSD-3-Clause"
