["Megaton contributors"]

"packages/cli/src/*.rs" = "MIT"
"packages/cli/build.rs" = "MIT"
"packages/cli-build/**/*.rs" = "MIT"
"packages/docker-build/*.rs" = "MIT"

"packages/lib/src/megaton/*.{s,c,cpp}" = "GPL-3.0-or-later"
"packages/lib/src/nximpl/*.{s,c,cpp}" = "GPL-3.0-or-later"
"packages/lib/include/exl/**/*.{h,hpp}" = "GPL-3.0-or-later"
"packages/lib/include/exl_armv8/**/*.{h,hpp}" = "GPL-3.0-or-later"
"packages/lib/include/megaton/*.{h,hpp}" = "GPL-3.0-or-later"
"packages/lib/include/megaton/{__internal,__priv}/*.{h,hpp}" = "GPL-3.0-or-later"
"packages/lib/**/*.rs" = "GPL-3.0-or-later"

"packages/test-mod/src/*.{c,cpp}" = "GPL-3.0-or-later"
"packages/test-mod/include/*.{h,hpp}" = "GPL-3.0-or-later"
"packages/test-mod/**/*.rs" = "GPL-3.0-or-later"

"packages/toolchain-build/**/*.rs" = "MIT"

# Unmodified files
# ["libnx Authors"]
# "packages/lib/src/external/libnx/*.s" = "ISC"
# ["Matthew Conte"]
# "packages/lib/include/megaton/__external/tlsf.h" = "BSD-3-Clause"
