version: '3'

includes:
  docs:
    taskfile: ./docs
    dir: ./docs

tasks:
  rustc:
    desc: Install custom rustc toolchain
    cmds:
    - ./rustc/install.sh
    
  run:
    dir: '{{.USER_WORKING_DIR}}'
    desc: Run megaton-hammer
    cmds:
    - echo "TODO"
