version: '3'

includes:
  common:
    taskfile: packages/mono-dev/task/common.yaml
    optional: true
    flatten: true

  cli:  { taskfile: packages/cli,  dir: packages/cli,  internal: true }
  docs: { taskfile: packages/docs, dir: packages/docs, internal: true }

tasks:
  install:
    - task: docs:install
    - task: install-mono

  install-mono:
    - rm -rf packages/mono-dev
    - git clone https://github.com/Pistonight/mono-dev --depth 1 packages/mono-dev

  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - task: cargo-binstall
        vars:
          PACKAGES: lisensor mdbook@0.4 mdbook-admonish cargo-watch live-server

  check:
    desc: run ALL of the checks
    cmds:
      - lisensor
      - task: cli:check

  build:
    desc: make sure everything can build
    cmds:
      - task: cli:build
      - task: docs:build

  license:
    desc: check or fix license notices (-- -f to fix)
    cmds:
      - lisensor {{.CLI_ARGS}}

