[package]
name = "megaton"
version = "0.0.0"
edition = "2021"
description = "Megaton runtime library"

[dependencies]
megaton-proc-macros = { path = "../macros" }
static_assertions = "1.1.0"

[lib]
path = "src/lib.rs"
name = "megaton"

