// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 Megaton contributors

#pragma once
#include <megaton/attributes.h>

#ifdef __cplusplus
extern "C" {
#endif

/** 
 * Rust entry point, generated by megaton::main macro in Rust.
 * Use megaton::rust_main instead of this function!!
 */
// NOLINTNEXTLINE(bugprone-reserved-identifier) FIXME
void __megaton_rs_main();

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
namespace megaton {
/** 
 * Call the rust entry point (the function annotated with #[megaton::main])
 */
inline_always_ void rust_main() {
    __megaton_rs_main();
}
}
#endif
