[book]
authors = ["Megaton Contributors"]
language = "en"
title = "Megaton"

[output.html]
default-theme = "frappe"
preferred-dark-theme = "frappe"
smart-punctuation = true
git-repository-url = "https://github.com/Pistonite/megaton"
additional-css = [
    "./theme/extra-css/catppuccin.css", 
    "./theme/extra-css/patch.css", 
]
