version: '3'

includes:
  builder:
    taskfile: ./builder
    dir: ./builder
    internal: true
  docker:
    taskfile: ../../mono-dev/task/docker.yaml
    internal: true
    optional: true
  cargo: 
    taskfile: ../../mono-dev/task/cargo.yaml
    internal: true
    optional: true

vars:
  DOCKER_IMAGE: ghcr.io/pistonite/megaton-build

tasks:
  check:
    - task: cargo:clippy-all
    - task: cargo:fmt-check
  fix:
    - task: cargo:fmt-fix

  build:
    cmds:
      - task: clean
      - task: copy-toolchain-build
      - task: copy-megaton-cmd
      - task: builder:build
      - task: build-w-builder

  build-w-builder:
    vars:
      GCC_VERSION:
        sh: head builder/temp/gcc-version.txt -n1 | sed -E 's/^gcc[^)]+\) ([0-9]+\.[0-9]+\.[0-9]+).*$/\1/'
      RUST_VERSION:
        sh: rustc -V | sed -E 's/rustc ([^ ]+) .*$/\1/'
    cmds:
      - task: docker:build
        vars:
          ARGS: --build-arg GCC_VERSION={{.GCC_VERSION}} --build-arg RUST_VERSION={{.RUST_VERSION}}
      - task: build-info
  
  build-info:
    # task bug that doesn't read the DOCKER_IMAGE var correctly?
    - docker run --rm ghcr.io/pistonite/megaton-build sh /root/print-info.sh > temp/info.txt
    - cat temp/info.txt
    - cat readme-header.md > README.md
    - cat temp/info.txt >> README.md
    - echo '```' >> README.md

  copy-toolchain-build:
    - rm -rf temp/toolchain-build
    - cp -R ../toolchain-build temp
    - cargo run --example prep_toolchain_build --quiet
    - cp ../../Cargo.lock temp/toolchain-build/Cargo.lock
    - cd temp/toolchain-build && cargo metadata --quiet > ../toolchain-build.metadata.json

  copy-megaton-cmd:
    - rm -rf temp/megaton-cmd
    - cp -R ../cli temp && mv temp/cli temp/megaton-cmd
    - rm -f temp/megaton-cmd/*.tar.gz
    - cargo run --example prep_megaton_cmd --quiet > temp/megaton-cmd.out # too noisy
    - cp ../../Cargo.lock temp/megaton-cmd/Cargo.lock
    - cd temp/megaton-cmd && cargo metadata --quiet > ../megaton-cmd.metadata.json

  clean:
    - rm -rf temp/*
    - mkdir -p temp

  nuke:
    - task: clean
    - task: docker:nuke

  publish:
    vars:
      TAG_VERSION:
        sh: grep -E ^version ../cli/Cargo.toml | head -n1 | sed -E 's/^version\s*=\s"([^"]+)"$/v\1/'
      TAG_COMMIT:
        sh: echo "sha-$(git rev-parse --short=7 HEAD)"
    cmds:
      - docker tag {{.DOCKER_IMAGE}}:latest {{.DOCKER_IMAGE}}:{{.TAG_VERSION}}
      - docker tag {{.DOCKER_IMAGE}}:latest {{.DOCKER_IMAGE}}:{{.TAG_COMMIT}}
      - docker push {{.DOCKER_IMAGE}}:latest
      - docker push {{.DOCKER_IMAGE}}:{{.TAG_VERSION}}
      - docker push {{.DOCKER_IMAGE}}:{{.TAG_COMMIT}}
      - cmd: echo 'https://github.com/orgs/Pistonite/packages/container/package/megaton-build'
        silent: true
