name: check
on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          rust: stable
          tool-cargo-binstall: lisensor
          ccpp-cmake: true
      - run: task check-non-dkp

  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          rust: stable
          tool-mdbook: true
      - run: task install-ci
      - run: task build-non-dkp

  dkp:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    container:
      image: devkitpro/devkita64
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          rust: stable
          tool-mdbook: true
          ccpp-cmake: true
      - run: task build-dkp
      - run: task check-dkp
